In [53]:
import pandas as pd
import numpy as np

# Load the uploaded file to analyze its structure and content
data = pd.read_csv(r'C:\Users\Ane\Downloads\DAS-Homeworks-main\Домашна 1\stock_market.csv')

# Display the first few rows of the dataset to understand its structure
data.info()

C:\Users\Ane\AppData\Local\Temp\ipykernel_18668\176866895.py:5: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(r'C:\Users\Ane\Downloads\DAS-Homeworks-main\Домашна 1\stock_market.csv')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299699 entries, 0 to 299698
Data columns (total 10 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        299699 non-null  object
 1   Last trade price            292699 non-null  object
 2   Max                         28357 non-null   object
 3   Min                         28357 non-null   object
 4   Avg. Price                  292699 non-null  object
 5   %chg.                       292688 non-null  object
 6   Volume                      299699 non-null  object
 7   Turnover in BEST in denars  299699 non-null  object
 8   Total turnover in denars    299699 non-null  object
 9   Issuer                      299699 non-null  object
dtypes: object(10)
memory usage: 22.9+ MB

In [69]:
unique_issuers = data['Issuer'].unique()

# Create a dictionary to store DataFrames for each issuer
issuer_dfs = {}

# Split the data for each issuer
for issuer in unique_issuers:
    issuer_dfs[issuer] = data[data['Issuer'] == issuer].copy()

In [73]:
issuer_dfs

{'SPOL':              Date  Last trade price  Max  Min Avg. Price %chg. Volume  \
 220708 2014-11-17               NaN  NaN  NaN        NaN   NaN      0
 220707 2014-11-18               NaN  NaN  NaN        NaN   NaN      0
 220706 2014-11-19               NaN  NaN  NaN        NaN   NaN      0
 220705 2014-11-20               NaN  NaN  NaN        NaN   NaN      0
 220704 2014-11-21               NaN  NaN  NaN        NaN   NaN      0
 ...           ...               ...  ...  ...        ...   ...    ...
 218255 2024-11-08               NaN  NaN  NaN        NaN   NaN      0
 218254 2024-11-11               NaN  NaN  NaN        NaN   NaN      0
 218253 2024-11-12               NaN  NaN  NaN        NaN   NaN      0
 218252 2024-11-13               NaN  NaN  NaN        NaN   NaN      0
 218251 2024-11-14               NaN  NaN  NaN        NaN   NaN      0

        Turnover in BEST in denars Total turnover in denars Issuer
 220708                          0                        0   SPOL
 220707                          0                        0   SPOL
 220706                          0                        0   SPOL
 220705                          0                        0   SPOL
 220704                          0                        0   SPOL
 ...                           ...                      ...    ...
 218255                          0                        0   SPOL
 218254                          0                        0   SPOL
 218253                          0                        0   SPOL
 218252                          0                        0   SPOL
 218251                          0                        0   SPOL

 [2458 rows x 10 columns],
 'ATPP':             Date  Last trade price  Max  Min Avg. Price %chg. Volume  \
 13613 2014-11-17             307.0  NaN  NaN        307   0.0      0
 13612 2014-11-18             307.0  NaN  NaN        307   0.0      0
 13611 2014-11-19             307.0  NaN  NaN        307   0.0      0
 13610 2014-11-20             307.0  NaN  NaN        307   0.0      0
 13609 2014-11-21             307.0  NaN  NaN        307   0.0      0
 ...          ...               ...  ...  ...        ...   ...    ...
 11534 2024-11-08             923.0  NaN  NaN        923   0.0      0
 11533 2024-11-11             923.0  NaN  NaN        923   0.0      0
 11532 2024-11-12             923.0  NaN  NaN        923   0.0      0
 11531 2024-11-13             923.0  NaN  NaN        923   0.0      0
 11530 2024-11-14             923.0  NaN  NaN        923   0.0      0

       Turnover in BEST in denars Total turnover in denars Issuer
 13613                          0                        0   ATPP
 13612                          0                        0   ATPP
 13611                          0                        0   ATPP
 13610                          0                        0   ATPP
 13609                          0                        0   ATPP
 ...                          ...                      ...    ...
 11534                          0                        0   ATPP
 11533                          0                        0   ATPP
 11532                          0                        0   ATPP
 11531                          0                        0   ATPP
 11530                          0                        0   ATPP

 [2084 rows x 10 columns],
 'ALKB':            Date  Last trade price  Max  Min Avg. Price %chg. Volume  \
 6611 2014-11-17           12000.0  NaN  NaN  12,000.00   0.0      0
 6610 2014-11-18           12000.0  NaN  NaN  12,000.00   0.0      0
 6609 2014-11-19           12000.0  NaN  NaN  12,000.00   0.0      0
 6608 2014-11-20           12000.0  NaN  NaN  12,000.00   0.0      0
 6607 2014-11-21           12000.0  NaN  NaN  12,000.00   0.0      0
 ...         ...               ...  ...  ...        ...   ...    ...
 4920 2024-11-08           18510.0  NaN  NaN  18,510.00   0.0      0
 4919 2024-11-11           18510.0  NaN  NaN  18,510.00   0.0      0
 4918 2024-11-12           18510.0  NaN  NaN  18,510.00   0.0      0
 4917 2024-11-13           18510.0  NaN  NaN  18,510.00   0.0      0
 4916 2024-11-14           18510.0  NaN  NaN  18,510.00   0.0      0

      Turnover in BEST in denars Total turnover in denars Issuer
 6611                          0                        0   ALKB
 6610                          0                        0   ALKB
 6609                          0                        0   ALKB
 6608                          0                        0   ALKB
 6607                          0                        0   ALKB
 ...                         ...                      ...    ...
 4920                          0                        0   ALKB
 4919                          0                        0   ALKB
 4918                          0                        0   ALKB
 4917                          0                        0   ALKB
 4916                          0                        0   ALKB

 [1696 rows x 10 columns],
 'ALK':            Date  Last trade price        Max        Min Avg. Price %chg.  \
 4915 2014-11-17            4900.0   4,900.00   4,861.00   4,892.84 -0.31
 4914 2014-11-18            5000.0   5,000.00   4,862.00   4,991.55  2.02
 4913 2014-11-19            5002.0   5,002.00   5,000.00   5,000.07  0.17
 4912 2014-11-20            5000.0   5,000.00   5,000.00   5,000.00   0.0
 4911 2014-11-21            5000.0   5,030.00   5,000.00   5,025.31  0.51
 ...         ...               ...        ...        ...        ...   ...
 2462 2024-11-08           23299.0  23,400.00  23,010.00  23,193.84  0.85
 2461 2024-11-11           23889.0  23,889.00  23,200.00  23,432.42  1.03
 2460 2024-11-12           23820.0  23,821.00  23,700.00  23,793.41  1.54
 2459 2024-11-13           24000.0  24,000.00  23,889.00  23,922.38  0.54
 2458 2024-11-14           24000.0  24,000.00  23,950.00  23,991.57  0.29

      Volume Turnover in BEST in denars Total turnover in denars Issuer
 4915    143                    699,676                  699,676    ALK
 4914  1,388                  6,928,265                6,928,265    ALK
 4913    305                  1,525,020                1,525,020    ALK
 4912    132                    660,000                  660,000    ALK
 4911  1,586                  7,970,141                7,970,141    ALK
 ...     ...                        ...                      ...    ...
 2462     64                  1,484,406                1,484,406    ALK
 2461     88                  2,062,053                2,062,053    ALK
 2460    485                 11,539,805               15,449,805    ALK
 2459    175                  4,186,417                8,110,017    ALK
 2458    408                  9,788,559               13,733,409    ALK

 [2458 rows x 10 columns],
 'STBP':              Date  Last trade price  Max  Min Avg. Price  %chg. Volume  \
 228082 2014-11-17             440.0  NaN  NaN        440    0.0      0
 228081 2014-11-18             440.0  NaN  NaN        440    0.0      0
 228080 2014-11-19             390.0  390  390        390 -11.36    250
 228079 2014-11-20             390.0  NaN  NaN        390    0.0      0
 228078 2014-11-21             390.0  NaN  NaN        390    0.0      0
 ...           ...               ...  ...  ...        ...    ...    ...
 225629 2024-11-08             650.0  NaN  NaN        650    0.0      0
 225628 2024-11-11             650.0  NaN  NaN        650    0.0      0
 225627 2024-11-12             650.0  NaN  NaN        650    0.0      0
 225626 2024-11-13             650.0  NaN  NaN        650    0.0      0
 225625 2024-11-14             650.0  NaN  NaN        650    0.0      0

        Turnover in BEST in denars Total turnover in denars Issuer
 228082                          0                        0   STBP
 228081                          0                        0   STBP
 228080                     97,500                   97,500   STBP
 228079                          0                        0   STBP
 228078                          0                        0   STBP
 ...                           ...                      ...    ...
 225629                          0                        0   STBP
 225628                          0                        0   STBP
 225627                          0                        0   STBP
 225626                          0                        0   STBP
 225625                          0                        0   STBP

 [2458 rows x 10 columns],
 'VROS':              Date  Last trade price  Max  Min Avg. Price %chg. Volume  \
 278733 2014-11-17            3900.0  NaN  NaN   3,900.00   0.0      0
 278732 2014-11-18            3900.0  NaN  NaN   3,900.00   0.0      0
 278731 2014-11-19            3900.0  NaN  NaN   3,900.00   0.0      0
 278730 2014-11-20            3900.0  NaN  NaN   3,900.00   0.0      0
 278729 2014-11-21            3900.0  NaN  NaN   3,900.00   0.0      0
 ...           ...               ...  ...  ...        ...   ...    ...
 276280 2024-11-08            7838.0  NaN  NaN   7,838.00   0.0      0
 276279 2024-11-11            7838.0  NaN  NaN   7,838.00   0.0      0
 276278 2024-11-12            7838.0  NaN  NaN   7,838.00   0.0      0
 276277 2024-11-13            7838.0  NaN  NaN   7,838.00   0.0      0
 276276 2024-11-14            7838.0  NaN  NaN   7,838.00   0.0      0

        Turnover in BEST in denars Total turnover in denars Issuer
 278733                          0                        0   VROS
 278732                          0                        0   VROS
 278731                          0                        0   VROS
 278730                          0                        0   VROS
 278729                          0                        0   VROS
 ...                           ...                      ...    ...
 276280                          0                        0   VROS
 276279                          0                        0   VROS
 276278                          0                        0   VROS
 276277                          0                        0   VROS
 276276                          0                        0   VROS

 [2458 rows x 10 columns],
 'KMB':             Date  Last trade price        Max        Min Avg. Price %chg.  \
 95814 2014-11-17            2150.0   2,151.00   2,150.00   2,150.22 -0.25
 95813 2014-11-18            2110.0   2,150.00   2,110.00   2,146.77 -0.16
 95812 2014-11-19            2083.0   2,086.00   2,083.00   2,083.47 -2.95
 95811 2014-11-20            2085.0   2,100.00   2,085.00   2,091.40  0.38
 95810 2014-11-21            2100.0   2,100.00   2,087.00   2,094.84  0.16
 ...          ...               ...        ...        ...        ...   ...
 93361 2024-11-08           24900.0  24,999.00  24,900.00  24,975.96   0.1
 93360 2024-11-11           24900.0  24,994.00  24,900.00  24,932.96 -0.17
 93359 2024-11-12           24770.0  24,850.00  24,770.00  24,788.51 -0.58
 93358 2024-11-13           24800.0  24,848.00  24,700.00  24,792.79  0.02
 93357 2024-11-14           24699.0  24,790.00  24,698.00  24,705.20 -0.35

       Volume Turnover in BEST in denars Total turnover in denars Issuer
 95814    244                    524,653                  524,653    KMB
 95813    413                    886,615                  886,615    KMB
 95812    581                  1,210,497                1,210,497    KMB
 95811     50                    104,570                  104,570    KMB
 95810     63                    131,975                  131,975    KMB
 ...      ...                        ...                      ...    ...
 93361    232                  5,794,422                5,794,422    KMB
 93360    380                  9,474,523               14,763,923    KMB
 93359    469                 11,625,809               11,625,809    KMB
 93358    489                 12,123,673               16,099,673    KMB
 93357  1,096                 27,076,903               31,052,903    KMB

 [2458 rows x 10 columns],
 'ZILUP':              Date  Last trade price  Max  Min Avg. Price %chg. Volume  \
 289874 2014-11-17             560.0  NaN  NaN        560   0.0      0
 289873 2014-11-18             560.0  NaN  NaN        560   0.0      0
 289872 2014-11-19             560.0  NaN  NaN        560   0.0      0
 289871 2014-11-20             560.0  NaN  NaN        560   0.0      0
 289870 2014-11-21             560.0  NaN  NaN        560   0.0      0
 ...           ...               ...  ...  ...        ...   ...    ...
 287421 2024-11-08             560.0  NaN  NaN        560   0.0      0
 287420 2024-11-11             560.0  NaN  NaN        560   0.0      0
 287419 2024-11-12             560.0  NaN  NaN        560   0.0      0
 287418 2024-11-13             560.0  NaN  NaN        560   0.0      0
 287417 2024-11-14             560.0  NaN  NaN        560   0.0      0

        Turnover in BEST in denars Total turnover in denars Issuer
 289874                          0                        0  ZILUP
 289873                          0                        0  ZILUP
 289872                          0                        0  ZILUP
 289871                          0                        0  ZILUP
 289870                          0                        0  ZILUP
 ...                           ...                      ...    ...
 287421                          0                        0  ZILUP
 287420                          0                        0  ZILUP
 287419                          0                        0  ZILUP
 287418                          0                        0  ZILUP
 287417                          0                        0  ZILUP

 [2458 rows x 10 columns],
 'INB':             Date  Last trade price       Max       Min Avg. Price %chg.  \
 77730 2014-11-17            5000.0       NaN       NaN   5,000.00   0.0
 77729 2014-11-18            5000.0       NaN       NaN   5,000.00   0.0
 77728 2014-11-19            5000.0       NaN       NaN   5,000.00   0.0
 77727 2014-11-20            5000.0       NaN       NaN   5,000.00   0.0
 77726 2014-11-21            5000.0       NaN       NaN   5,000.00   0.0
 ...          ...               ...       ...       ...        ...   ...
 75277 2024-11-08            3700.0       NaN       NaN   3,700.00   0.0
 75276 2024-11-11            3700.0       NaN       NaN   3,700.00   0.0
 75275 2024-11-12            3702.0  3,702.00  3,700.00   3,701.54  0.04
 75274 2024-11-13            3702.0  3,703.00  3,702.00   3,702.30  0.02
 75273 2024-11-14            3702.0       NaN       NaN   3,702.30   0.0

       Volume Turnover in BEST in denars Total turnover in denars Issuer
 77730      0                          0                        0    INB
 77729      0                          0                        0    INB
 77728      0                          0                        0    INB
 77727      0                          0                        0    INB
 77726      0                          0                        0    INB
 ...      ...                        ...                      ...    ...
 75277      0                          0                        0    INB
 75276      0                          0                        0    INB
 75275    648                  2,398,596                2,398,596    INB
 75274     82                    303,589                  303,589    INB
 75273      0                          0                        0    INB

 [2458 rows x 10 columns],
 'GIMS':             Date  Last trade price  Max  Min Avg. Price %chg. Volume  \
 63517 2014-11-17            6500.0  NaN  NaN   6,500.00   0.0      0
 63516 2014-11-18            6500.0  NaN  NaN   6,500.00   0.0      0
 63515 2014-11-19            6500.0  NaN  NaN   6,500.00   0.0      0
 63514 2014-11-20            6500.0  NaN  NaN   6,500.00   0.0      0
 63513 2014-11-21            6500.0  NaN  NaN   6,500.00   0.0      0
 ...          ...               ...  ...  ...        ...   ...    ...
 61463 2024-11-08            9240.0  NaN  NaN   9,240.00   0.0      0
 61462 2024-11-11            9240.0  NaN  NaN   9,240.00   0.0      0
 61461 2024-11-12            9240.0  NaN  NaN   9,240.00   0.0      0
 61460 2024-11-13            9240.0  NaN  NaN   9,240.00   0.0      0
 61459 2024-11-14            9240.0  NaN  NaN   9,240.00   0.0      0

       Turnover in BEST in denars Total turnover in denars Issuer
 63517                          0                        0   GIMS
 63516                          0                        0   GIMS
 63515                          0                        0   GIMS
 63514                          0                        0   GIMS
 63513                          0                        0   GIMS
 ...                          ...                      ...    ...
 61463                          0                        0   GIMS
 61462                          0                        0   GIMS
 61461                          0                        0   GIMS
 61460                          0                        0   GIMS
 61459                          0                        0   GIMS

 [2059 rows x 10 columns],
 'FUBT':             Date  Last trade price  Max  Min Avg. Price %chg. Volume  \
 54329 2014-11-17             500.0  NaN  NaN        500   0.0      0
 54328 2014-11-18             500.0  NaN  NaN        500   0.0      0
 54327 2014-11-19             500.0  NaN  NaN        500   0.0      0
 54326 2014-11-20             500.0  NaN  NaN        500   0.0      0
 54325 2014-11-21             500.0  NaN  NaN        500   0.0      0
 ...          ...               ...  ...  ...        ...   ...    ...
 51876 2024-11-08            2101.0  NaN  NaN   2,101.00   0.0      0
 51875 2024-11-11            2101.0  NaN  NaN   2,101.00   0.0      0
 51874 2024-11-12            2101.0  NaN  NaN   2,101.00   0.0      0
 51873 2024-11-13            2101.0  NaN  NaN   2,101.00   0.0      0
 51872 2024-11-14            2101.0  NaN  NaN   2,101.00   0.0      0

       Turnover in BEST in denars Total turnover in denars Issuer
 54329                          0                        0   FUBT
 54328                          0                        0   FUBT
 54327                          0                        0   FUBT
 54326                          0                        0   FUBT
 54325                          0                        0   FUBT
 ...                          ...                      ...    ...
 51876                          0                        0   FUBT
 51875                          0                        0   FUBT
 51874                          0                        0   FUBT
 51873                          0                        0   FUBT
 51872                          0                        0   FUBT

 [2458 rows x 10 columns],
 'RZUS':              Date  Last trade price  Max  Min Avg. Price %chg. Volume  \
 197886 2014-11-17             101.0  NaN  NaN        101   0.0      0
 197885 2014-11-18             101.0  NaN  NaN        101   0.0      0
 197884 2014-11-19             101.0  NaN  NaN        101   0.0      0
 197883 2014-11-20             104.0  104  104        104  2.97    159
 197882 2014-11-21             104.0  NaN  NaN        104   0.0      0
 ...           ...               ...  ...  ...        ...   ...    ...
 195433 2024-11-08              45.0   45   45         45     0  1,000
 195432 2024-11-11              45.0   45   45         45     0  1,800
 195431 2024-11-12              45.0   45   45         45     0  1,631
 195430 2024-11-13              45.0   45   45         45     0  3,000
 195429 2024-11-14              45.0  NaN  NaN         45     0      0

        Turnover in BEST in denars Total turnover in denars Issuer
 197886                          0                        0   RZUS
 197885                          0                        0   RZUS
 197884                          0                        0   RZUS

In [54]:
# Data preprocessing
# Convert 'Date' column to datetime
data['Date'] = pd.to_datetime(data['Date'], errors='coerce')

# Remove rows with invalid dates
data = data.dropna(subset=['Date'])

# Sort by date in ascending order for time-series analysis
data = data.sort_values(by='Date')

# Remove commas from 'Last trade price' and convert to numeric
data['Last trade price'] = pd.to_numeric(data['Last trade price'].str.replace(',', ''), errors='coerce')

# Select necessary columns for technical analysis
technical_data = data[['Date', 'Last trade price']].dropna()

# Rename columns for easier handling
technical_data.rename(columns={'Last trade price': 'Price'}, inplace=True)

technical_data.head()

             Date    Price
13613  2014-11-17    307.0
6611   2014-11-17  12000.0
4915   2014-11-17   4900.0
228082 2014-11-17    440.0
278733 2014-11-17   3900.0

In [55]:
import ta

# Function to calculate technical indicators
def calculate_indicators(df):
    # Calculate RSI
    df['RSI_1D'] = ta.momentum.RSIIndicator(close=df['Price'], window=14).rsi()
    
    # Calculate Stochastic Oscillator (using High, Low, Close, but here using Price for simplicity)
    df['Stoch_1D'] = ta.momentum.StochRSIIndicator(close=df['Price'], window=14).stochrsi()
    
    # Calculate MACD (Moving Average Convergence Divergence)
    macd = ta.trend.MACD(close=df['Price'])
    df['MACD_1D'] = macd.macd_diff()
    
    # Calculate Williams %R
    df['Williams_%R_1D'] = ta.momentum.WilliamsRIndicator(
        high=df['Price'], low=df['Price'], close=df['Price'], lbp=14
    ).williams_r()
    
    # Calculate CCI (Commodity Channel Index)
    df['CCI_1D'] = ta.trend.CCIIndicator(
        high=df['Price'], low=df['Price'], close=df['Price'], window=14
    ).cci()
    weights = np.array(range(1, 15))
    weights = weights / weights.sum()
    
    df['SMA_1D'] = df['Price'].rolling(window=14).mean()
    df['EMA_1D'] = df['Price'].ewm(span=14, adjust=False).mean()
    
    # Use convolution for WMA calculation
    df['WMA_1D'] = df['Price'].rolling(window=14).apply(lambda x: np.dot(x, weights), raw=True)
    
    df['HMA_1D'] = (2 * df['EMA_1D'] - df['SMA_1D']).rolling(14).mean()
    df['TEMA_1D'] = 3 * df['EMA_1D'] - 3 * df['EMA_1D'].ewm(span=14).mean() + df['EMA_1D'].ewm(span=14).mean()
    

    return df

# Calculate indicators for the given dataset
technical_data = calculate_indicators(technical_data)

# Show a sample of the processed dataset
technical_data

,Date,Price,RSI_1D,Stoch_1D,MACD_1D,Williams_%R_1D,CCI_1D,SMA_1D,EMA_1D,WMA_1D,HMA_1D,TEMA_1D
13613,2014-11-17,307.0,NaN,NaN,NaN,NaN,NaN,NaN,307.000000,NaN,NaN,307.000000
6611,2014-11-17,12000.0,NaN,NaN,NaN,NaN,NaN,NaN,1866.066667,NaN,NaN,3313.771429
4915,2014-11-17,4900.0,NaN,NaN,NaN,NaN,NaN,NaN,2270.591111,NaN,NaN,3665.257204
228082,2014-11-17,440.0,NaN,NaN,NaN,NaN,NaN,NaN,2026.512296,NaN,NaN,2655.694249
278733,2014-11-17,3900.0,NaN,NaN,NaN,NaN,NaN,NaN,2276.310657,NaN,NaN,3110.592702
...,...,...,...,...,...,...,...,...,...,...,...,...
119924,2024-11-14,89458.0,78.977360,1.000000,5437.600932,-0.000000,451.159856,9242.928571,15342.140746,15047.095238,5078.174942,34739.508937
176560,2024-11-14,315.0,47.814032,0.016257,2886.399693,-99.748232,-50.343473,9261.857143,13338.521980,13856.704762,5917.877466,26676.635218
69826,2024-11-14,1790.0,48.178401,0.026318,1212.455954,-98.097753,-42.823861,9379.000000,11798.719049,12860.457143,6629.196525,20689.425442
127267,2024-11-14,99.0,47.766636,0.013300,-28.699037,-99.989929,-52.259421,9363.571429,10238.756509,11623.123810,7191.116921,15240.100314
0,2024-11-14,1650.0,48.203903,0.027124,-726.564753,-98.254409,-41.164298,9010.000000,9093.588975,10594.647619,7527.212556,11443.129879

In [57]:
# Calculate RSI (Relative Strength Index)
def calculate_rsi(prices, window=14):
    delta = prices.diff(1)
    gain = delta.where(delta > 0, 0)
    loss = -delta.where(delta < 0, 0)
    
    avg_gain = gain.rolling(window=window, min_periods=1).mean()
    avg_loss = loss.rolling(window=window, min_periods=1).mean()
    
    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))
    return rsi

# Calculate SMA (Simple Moving Average)
def calculate_sma(prices, window=14):
    return prices.rolling(window=window).mean()

# Add RSI and SMA to the dataset
technical_data['RSI_1D'] = calculate_rsi(technical_data['Price'], window=14)
technical_data['SMA_1D'] = calculate_sma(technical_data['Price'], window=14)

# Display a sample of the dataset with RSI and SMA
technical_data

,Date,Price,RSI_1D,Stoch_1D,MACD_1D,Williams_%R_1D,CCI_1D,SMA_1D,EMA_1D,WMA_1D,HMA_1D,TEMA_1D
13613,2014-11-17,307.0,NaN,NaN,NaN,NaN,NaN,NaN,307.000000,NaN,NaN,307.000000
6611,2014-11-17,12000.0,100.000000,NaN,NaN,NaN,NaN,NaN,1866.066667,NaN,NaN,3313.771429
4915,2014-11-17,4900.0,62.219976,NaN,NaN,NaN,NaN,NaN,2270.591111,NaN,NaN,3665.257204
228082,2014-11-17,440.0,50.285985,NaN,NaN,NaN,NaN,NaN,2026.512296,NaN,NaN,2655.694249
278733,2014-11-17,3900.0,56.725190,NaN,NaN,NaN,NaN,NaN,2276.310657,NaN,NaN,3110.592702
...,...,...,...,...,...,...,...,...,...,...,...,...
119924,2024-11-14,89458.0,84.922613,1.000000,5437.600932,-0.000000,451.159856,9242.928571,15342.140746,15047.095238,5078.174942,34739.508937
176560,2024-11-14,315.0,50.061397,0.016257,2886.399693,-99.748232,-50.343473,9261.857143,13338.521980,13856.704762,5917.877466,26676.635218
69826,2024-11-14,1790.0,50.377564,0.026318,1212.455954,-98.097753,-42.823861,9379.000000,11798.719049,12860.457143,6629.196525,20689.425442
127267,2024-11-14,99.0,49.950619,0.013300,-28.699037,-99.989929,-52.259421,9363.571429,10238.756509,11623.123810,7191.116921,15240.100314
0,2024-11-14,1650.0,48.843317,0.027124,-726.564753,-98.254409,-41.164298,9010.000000,9093.588975,10594.647619,7527.212556,11443.129879

In [65]:
def generate_signals(df):
        # Buy/Sell signals for SMA
    df['SMA_Signal'] = np.where(df['SMA_1D'] > df['Price'], 'Buy',
                               np.where(df['SMA_1D'] < df['Price'], 'Sell', 'Hold'))
    
    # Buy/Sell signals for EMA
    df['EMA_Signal'] = np.where(df['EMA_1D'] > df['Price'], 'Buy',
                               np.where(df['EMA_1D'] < df['Price'], 'Sell', 'Hold'))
    
    # Buy/Sell signals for RSI
    df['RSI_Signal'] = np.where(df['RSI_1D'] < 30, 'Buy',
                               np.where(df['RSI_1D'] > 70, 'Sell', 'Hold'))
    
    # Buy/Sell signals for MACD
    df['MACD_Signal'] = np.where(df['MACD_1D'] > 0, 'Buy',
                                np.where(df['MACD_1D'] < 0, 'Sell', 'Hold'))
    
    # Additional signals based on Williams %R
    df['Williams_Signal'] = np.where(df['Williams_%R_1D'] < -80, 'Buy',
                                    np.where(df['Williams_%R_1D'] > -20, 'Sell', 'Hold'))
    
    # CCI signals
    df['CCI_Signal'] = np.where(df['CCI_1D'] < -100, 'Buy',
                               np.where(df['CCI_1D'] > 100, 'Sell', 'Hold'))
    
    # Count buy and sell signals for each row
    signal_columns = ['SMA_Signal', 'EMA_Signal', 'RSI_Signal', 
                     'MACD_Signal', 'Williams_Signal', 'CCI_Signal']
    
    df['Buy_Count'] = (df[signal_columns] == 'Buy').sum(axis=1)
    df['Sell_Count'] = (df[signal_columns] == 'Sell').sum(axis=1)
    
    # Generate composite signal based on majority
    df['Composite_Signal'] = np.where(df['Buy_Count'] > df['Sell_Count'], 'Buy',
                                     np.where(df['Sell_Count'] > df['Buy_Count'], 'Sell', 'Hold'))
    
    # Clean up temporary columns
    df = df.drop(['Buy_Count', 'Sell_Count'], axis=1)
    
    return df


generate_signals=generate_signals(technical_data)

In [67]:
generate_signals

,Date,Price,RSI_1D,Stoch_1D,MACD_1D,Williams_%R_1D,CCI_1D,SMA_1D,EMA_1D,WMA_1D,HMA_1D,TEMA_1D,SMA_Signal,EMA_Signal,RSI_Signal,MACD_Signal,Williams_Signal,CCI_Signal,Composite_Signal
13613,2014-11-17,307.0,NaN,NaN,NaN,NaN,NaN,NaN,307.000000,NaN,NaN,307.000000,Hold,Hold,Hold,Hold,Hold,Hold,Hold
6611,2014-11-17,12000.0,100.000000,NaN,NaN,NaN,NaN,NaN,1866.066667,NaN,NaN,3313.771429,Hold,Sell,Sell,Hold,Hold,Hold,Sell
4915,2014-11-17,4900.0,62.219976,NaN,NaN,NaN,NaN,NaN,2270.591111,NaN,NaN,3665.257204,Hold,Sell,Hold,Hold,Hold,Hold,Sell
228082,2014-11-17,440.0,50.285985,NaN,NaN,NaN,NaN,NaN,2026.512296,NaN,NaN,2655.694249,Hold,Buy,Hold,Hold,Hold,Hold,Buy
278733,2014-11-17,3900.0,56.725190,NaN,NaN,NaN,NaN,NaN,2276.310657,NaN,NaN,3110.592702,Hold,Sell,Hold,Hold,Hold,Hold,Sell
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119924,2024-11-14,89458.0,84.922613,1.000000,5437.600932,-0.000000,451.159856,9242.928571,15342.140746,15047.095238,5078.174942,34739.508937,Sell,Sell,Sell,Buy,Sell,Sell,Sell
176560,2024-11-14,315.0,50.061397,0.016257,2886.399693,-99.748232,-50.343473,9261.857143,13338.521980,13856.704762,5917.877466,26676.635218,Buy,Buy,Hold,Buy,Buy,Hold,Buy
69826,2024-11-14,1790.0,50.377564,0.026318,1212.455954,-98.097753,-42.823861,9379.000000,11798.719049,12860.457143,6629.196525,20689.425442,Buy,Buy,Hold,Buy,Buy,Hold,Buy
127267,2024-11-14,99.0,49.950619,0.013300,-28.699037,-99.989929,-52.259421,9363.571429,10238.756509,11623.123810,7191.116921,15240.100314,Buy,Buy,Hold,Sell,Buy,Hold,Buy
0,2024-11-14,1650.0,48.843317,0.027124,-726.564753,-98.254409,-41.164298,9010.000000,9093.588975,10594.647619,7527.212556,11443.129879,Buy,Buy,Hold,Sell,Buy,Hold,Buy